# Welcome to Jekyll!
#
# This config file controls the main settings for the site.

# Basic Site Settings
locale                   : "zh-CN"
site_theme               : "default"
title                    : "刘长羽 | Communication · Digital Marketing "
title_separator          : "-"
name                     : &name "刘长羽"
description              : &description "新闻与传播硕士｜数字营销｜AI｜个人作品集"
url                      : https://lunaalovegood2004-del.github.io/
baseurl                  : ""
repository               : "lunaalovegood2004-del/lunaalovegood2004-del.github.io"

# Site Author
author:
  avatar           : "https://raw.githubusercontent.com/lunaalovegood2004-del/lunaalovegood2004-del.github.io/master/images/B27A0067%281%E5%AF%B8%E7%94%B5%E5%AD%90%E7%89%88%29.PNG"
  name             : "刘长羽"
  pronouns         :
  bio              : "新闻与传播硕士在读｜数字营销 × AI"
  location         : "南京"
  employer         : "南京大学"
  uri              :
  email            : "13525991276@163.com"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory     :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "lunaalovegood2004-del"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook        :
  flickr          :
  foursquare       :
  goodreads        :
  google_plus      :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram        :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image:
og_description:
social:
  type                   : "Person"
  name                   : "刘长羽"
  links:
    - "https://github.com/lunaalovegood2004-del"

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
